print("Gépeld be a téglalap A oldalának hosszát")
a=int(input())
print("Gépeld be a téglalap B oldalának hosszát")
b=int(input())
kerulet=2*(a+b)
terulet=a*b
print("A téglalap kerülete:",kerulet)
print("A téglalap területe:",terulet)
print("Gépeld be a háromszög A oldalának hosszát")
a=int(input())
print("Gépeld be a háromszög B oldalának hosszát")
b=int(input())
print("Gépeld be a háromszög C oldalának hosszát")
c=int(input())
print("Gépeld be a háromszög magasságát")
ma=int(input())
kerulet=a+b+c
terulet=(a*ma)/2
print("A háromszög kerülete:",kerulet)
print("A háromszög területe:",terulet)